'use client'
import { useMemo, useState } from 'react'
import PostCard, { type Post } from '@/components/PostCard'
import Button from '@/components/ui/Button'
type Model={id:string;username:string;display_name:string|null;avatar_url:string|null;is_verified:boolean;is_online:boolean}
export type RawPost={id:string;creator_id:string;title:string|null;body:string|null;post_type:'free'|'premium'|'ppv';ppv_price_cents:number|null;like_count:number;comment_count:number;published_at:string|null;comments_disabled:boolean;display_like_count:number|null;media:Array<{url:string;media_type:string;sort_order:number}>}
type Settings={id:string;enabled:boolean;post_id:string|null;animation_delay_ms:number;updated_at:string}|null
export default function FirstLoginSettings({models,posts,initialSettings,deliveredCount}:{models:Model[];posts:RawPost[];initialSettings:Settings;deliveredCount:number}){
 const initialPost=posts.find(p=>p.id===initialSettings?.post_id);const[modelId,setModelId]=useState(initialPost?.creator_id??models[0]?.id??'');const[postId,setPostId]=useState(initialSettings?.post_id??'');const[enabled,setEnabled]=useState(initialSettings?.enabled??false);const[delay,setDelay]=useState(initialSettings?.animation_delay_ms??1000);const[updatedAt,setUpdatedAt]=useState(initialSettings?.updated_at??null);const[saving,setSaving]=useState(false);const[testing,setTesting]=useState(false);const[error,setError]=useState<string|null>(null);const[success,setSuccess]=useState<string|null>(null)
 const model=models.find(m=>m.id===modelId),selected=posts.find(p=>p.id===postId),options=posts.filter(p=>p.creator_id===modelId)
 const preview=useMemo<Post|null>(()=>{if(!selected||!model)return null;const media=[...(selected.media??[])].sort((a,b)=>a.sort_order-b.sort_order),name=model.display_name??model.username;return{id:selected.id,creatorId:model.id,creator:{name,username:model.username,initials:name.slice(0,2).toUpperCase(),verified:model.is_verified,avatarUrl:model.avatar_url},content:selected.body??'',hasMedia:media.length>0,mediaItems:media.map(m=>({url:m.url,type:m.media_type as'image'|'video'})),type:selected.post_type,ppvPrice:selected.ppv_price_cents?selected.ppv_price_cents/100:undefined,likes:selected.like_count,comments:selected.comment_count,publishedAt:selected.published_at,isOnline:model.is_online,commentsDisabled:selected.comments_disabled,displayLikeCount:selected.display_like_count}},[selected,model])
 async function save(){setSaving(true);setError(null);setSuccess(null);const res=await fetch('/api/admin/first-login',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled,post_id:postId||null,animation_delay_ms:delay})});const data=await res.json();if(!res.ok)setError(data.error??'Save failed');else{setUpdatedAt(data.settings.updated_at);setSuccess('Settings saved.')}setSaving(false)}
 async function test(){if(!confirm('Replace only your own test post? Other users are not affected.'))return;setTesting(true);setError(null);const res=await fetch('/api/admin/first-login',{method:'POST'});const data=await res.json();if(!res.ok)setError(data.error??'Test failed');else setSuccess('Test post prepared. Open Feed to see it.');setTesting(false)}
 return <div className="p-4 sm:p-6 lg:p-8 max-w-3xl"><h1 className="text-2xl font-bold">First Login Post</h1><p className="text-sm text-zinc-500 mt-1 mb-6">Choose the post new members see after their first sign-in.</p>{error&&<p className="mb-4 text-sm text-red-400">{error}</p>}{success&&<p className="mb-4 text-sm text-emerald-400">{success}</p>}<div className="space-y-5 bg-zinc-900 border border-zinc-800 rounded-2xl p-5"><label className="flex justify-between"><span>Enabled</span><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/></label><label className="block text-sm">Creator<select className="mt-1 w-full bg-zinc-950 border border-zinc-800 rounded-xl p-2" value={modelId} onChange={e=>{setModelId(e.target.value);setPostId('')}}>{models.map(m=><option key={m.id} value={m.id}>{m.display_name??m.username}</option>)}</select></label><label className="block text-sm">Post<select className="mt-1 w-full bg-zinc-950 border border-zinc-800 rounded-xl p-2" value={postId} onChange={e=>setPostId(e.target.value)}><option value="">Select a post</option>{options.map(p=><option key={p.id} value={p.id}>{p.title??p.body?.slice(0,60)??'(untitled)'}</option>)}</select></label><label className="block text-sm">Animation delay: {delay} ms<input className="w-full" type="range" min="500" max="3000" step="100" value={delay} onChange={e=>setDelay(Number(e.target.value))}/></label><div className="text-xs text-zinc-500">Delivered: {deliveredCount} · Last changed: {updatedAt?new Date(updatedAt).toLocaleString():'Never'}</div><Button loading={saving} disabled={!postId} onClick={save}>Save Changes</Button><div className="border-t border-zinc-800 pt-4"><p className="text-xs text-zinc-500 mb-2">Test tools affect only your account.</p><Button variant="outline" loading={testing} onClick={test}>Test for my account</Button></div></div>{preview&&<div className="mt-6"><h2 className="text-sm font-semibold mb-3">Preview</h2><PostCard post={preview} isSubscribed unlockedPosts={new Set()} onUnlock={()=>{}} onSubscribe={()=>{}}/></div>}</div>
}
