'use client'
import { useState } from 'react'
import Link from 'next/link'
type Promo = { id: string; code: string; name: string; discount_percent: number; is_active: boolean }
export default function PromoCodesClient({ initial }: { initial: Promo[] }) {
  const [rows, setRows] = useState(initial); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null)
  async function create() { const code = window.prompt('Code')?.trim(); if (!code) return; const pct = Number(window.prompt('Discount percentage (1–90)', '10')); if (!Number.isInteger(pct) || pct < 1 || pct > 90) { setError('Discount must be 1–90%'); return }; setBusy(true); const r = await fetch('/api/admin/promo-codes', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ code, name: code, discount_percent: pct }) }); const d = await r.json(); if (!r.ok) setError(d.error); else setRows(x => [d.promoCode, ...x]); setBusy(false) }
  async function toggle(p: Promo) { setBusy(true); const r = await fetch('/api/admin/promo-codes/' + p.id, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ is_active: !p.is_active }) }); const d = await r.json(); if (r.ok) setRows(x => x.map(v => v.id === p.id ? d.promoCode : v)); else setError(d.error); setBusy(false) }
 return <div className="p-4 sm:p-6 lg:p-8"><div className="flex items-center justify-between mb-6"><div><h1 className="text-2xl font-bold">Promo codes</h1><p className="text-sm text-zinc-500">Server-validated discounts</p></div><button disabled={busy} onClick={create} className="px-4 py-2 rounded-xl bg-pink-500 text-sm font-semibold">Create promo code</button></div>{error && <p className="mb-4 text-sm text-red-400">{error}</p>}<div className="bg-zinc-900 border border-zinc-800 rounded-2xl overflow-hidden"><table className="w-full text-sm"><thead><tr className="text-left text-zinc-500 border-b border-zinc-800"><th className="p-4">Code</th><th className="p-4">Discount</th><th className="p-4">Status</th><th className="p-4">Action</th></tr></thead><tbody>{rows.map(p => <tr key={p.id} className="border-b border-zinc-800/60"><td className="p-4 font-mono"><Link href={`/admin/promo-codes/${p.id}`} className="hover:text-pink-400">{p.code}</Link><span className="block text-xs text-zinc-500 font-sans">{p.name}</span></td><td className="p-4">{p.discount_percent}%</td><td className="p-4">{p.is_active ? 'Active' : 'Inactive'}</td><td className="p-4"><button disabled={busy} onClick={() => toggle(p)} className="text-pink-400">{p.is_active ? 'Deactivate' : 'Activate'}</button></td></tr>)}</tbody></table></div></div>
}
